[package]
name = "ziggurat"
version = "0.1.0"
authors = ["Niklas Long <niklas@equilibrium.co>, Mirko von Leipzig <mirko@equilibrium.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
hex = "0.4.3"
lazy_static = "1.4.0"
rand = "0.8.3"
rand_chacha = "0.3.0"
sha2 = "0.9.3"
toml = "0.5.8"

[dependencies.tokio]
version = "1"
features = [ "full" ]

[dependencies.serde]
version = "1"
features = [ "derive" ]
